#!/usr/bin/env node
// Bundle the AI-tool entry points into self-contained Node scripts (tool-dist/) and write
// the generated tool descriptions (tool/tools.json, tool/openapi.json). Run: npm run build:tool
import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const entries = { 'mcp-stdio': 'src/tool/mcp-stdio.ts', 'http-server': 'src/tool/http-server.ts', cli: 'src/tool/cli.ts', core: 'src/tool/schemas-entry.ts' };
mkdirSync('tool-dist', { recursive: true });
await build({
  entryPoints: entries,
  outdir: 'tool-dist',
  outExtension: { '.js': '.mjs' },
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'none',
  banner: { js: '// Generated by scripts/tool/build.mjs from src/tool/*.ts - do not edit.\nimport { createRequire as __cr } from "node:module"; const require = __cr(import.meta.url);' },
  logLevel: 'warning',
});
const { genericToolList, openApiDocument } = await import(pathToFileURL('tool-dist/core.mjs').href);
mkdirSync('tool', { recursive: true });
writeFileSync('tool/tools.json', JSON.stringify(genericToolList('remote'), null, 2) + '\n');
writeFileSync('tool/tools.local.json', JSON.stringify(genericToolList('local'), null, 2) + '\n');
writeFileSync('tool/openapi.json', JSON.stringify(openApiDocument(), null, 2) + '\n');
console.log('built tool-dist/{mcp-stdio,http-server,cli,core}.mjs and tool/{tools,tools.local,openapi}.json');
