#!/usr/bin/env python3
"""Reference output of the Python emotion cues for tests/emotion-features.test.ts.

Also writes emotion_model_reference.json: outputs of data/emotion/valence_arousal.json for fixed
inputs, computed here independently of the app, so the app's input layout is checked.

Signal (10 s, 16 kHz): a C-major chord with clicks at 120 BPM, then an A-minor chord with a
semitone clash and noise bursts at 90 BPM. The PCM is stored as base64 int16 so both sides read
identical samples.
"""
import base64
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import emotion_features as F  # noqa: E402
from vgmidi_eval import piece_features, window_cues  # noqa: E402


def signal():
    sr = F.SR
    t = np.arange(10 * sr) / sr
    rng = np.random.default_rng(1)
    y = np.zeros_like(t)
    a = t < 5
    for f in (130.81, 261.63, 329.63, 392.0):
        y[a] += 0.12 * np.sin(2 * np.pi * f * t[a])
    b = ~a
    for f in (110.0, 220.0, 261.63, 329.63, 349.23):
        y[b] += 0.1 * np.sin(2 * np.pi * f * t[b])
    for beat, (s, e) in ((0.5, (0, 5)), (60 / 90, (5, 10))):
        for c in np.arange(s, e, beat):
            i = int(c * sr)
            n = int(0.03 * sr)
            y[i:i + n] += (0.5 if c >= 5 else 0.3) * rng.standard_normal(n) * np.exp(-np.arange(n) / (0.006 * sr))
    return np.clip(y, -1, 1)


def main():
    import librosa
    y = signal()
    q = (y * 32767).round().astype('<i2')
    y = q.astype(np.float64) / 32767
    P = piece_features(y, librosa.filters.mel(sr=F.SR, n_fft=512, n_mels=96), None, None)
    aud = P['db'][P['db'] > F.SILENCE_DB]
    ref = float(np.percentile(aud, 95))
    times = [3.0, 4.5, 6.0, 8.0, 10.0]
    out = {
        'note': 'Generated by scripts/validation/make_emotion_fixture.py from scripts/validation/emotion_features.py',
        'pcm16': base64.b64encode(q.tobytes()).decode(),
        'pieceRef': ref,
        'frames': {'centroid': [float(v) for v in P['centroid'][::25]], 'power': [float(v) for v in P['tot'][::25]],
                   'chroma10': [float(v) for v in P['chroma'][10]], 'chroma60': [float(v) for v in P['chroma'][60]],
                   'nSmall': int(len(P['centroid'])), 'nChroma': int(len(P['chroma']))},
        'cues': [{'t': t, **{k: float(v) for k, v in window_cues(P, t, ref).items()}} for t in times],
    }
    path = os.path.join(ROOT, 'tests', 'fixtures-model', 'emotion_features_reference.json')
    json.dump(out, open(path, 'w'))
    for c in out['cues']:
        print({k: round(v, 3) for k, v in c.items()})


def model_fixture():
    """Expected outputs of data/emotion/valence_arousal.json for fixed inputs (checks the app's input layout)."""
    from vgmidi_eval import MODEL_CUES, MODEL_TAGS
    doc = json.load(open(os.path.join(ROOT, 'data', 'emotion', 'valence_arousal.json')))
    rng = np.random.default_rng(3)
    out = {}
    for name, m in doc['models'].items():
        nc, nt = len(MODEL_CUES), (len(MODEL_TAGS) if 'tags' in name else 0)
        mu = np.array(m['valence']['mean'])
        raw_mu = np.concatenate([mu[:nc], mu[2 * nc:2 * nc + nt]]) if nt else mu[:nc]
        raw_sd = np.concatenate([np.array(m['valence']['sd'])[:nc], np.array(m['valence']['sd'])[2 * nc:2 * nc + nt]]) if nt else np.array(m['valence']['sd'])[:nc]
        rows = raw_mu + raw_sd * rng.standard_normal((6, nc + nt)) * 1.5
        rows[0, 0] = raw_mu[0] + 10 * raw_sd[0]  # exercises the z clip
        piece_mean = rows.mean(axis=0)
        exp = {}
        for dim in ('valence', 'arousal'):
            d = m[dim]
            X = np.hstack([rows[:, :nc], rows[:, :nc] - piece_mean[:nc]] + ([rows[:, nc:], rows[:, nc:] - piece_mean[nc:]] if nt else []))
            Z = np.clip((X - np.array(d['mean'])) / np.array(d['sd']), -m['zClip'], m['zClip'])
            exp[dim] = (d['intercept'] + Z @ np.array(d['coef'])).tolist()
        out[name] = {'rows': rows.tolist(), 'pieceMean': piece_mean.tolist(), 'expected': exp}
    json.dump(out, open(os.path.join(ROOT, 'tests', 'fixtures-model', 'emotion_model_reference.json'), 'w'))


if __name__ == '__main__':
    main()
    model_fixture()
